Update test.yml

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -7,7 +7,6 @@ on:
     branches: [ "*" ]
   workflow_dispatch:
 
-
 jobs:
   build:
     runs-on: ubuntu-latest
@@ -25,5 +24,15 @@ jobs:
       - name: 'Running A11y test on Automate'
         run: |
           export BROWSERSTACK_CONFIG_FILE=src/test/resources/conf/capabilities/browserstack.yml
-        
           mvn clean test -P bstack-parallel-browsers
+
+      - name: 'Check for Assertion Failures'
+        if: always()
+        run: |
+          echo "Checking for assertion failures..."
+          if grep -q "AssertionError" target/surefire-reports/*.txt; then
+            echo "❌ Assertion failures detected in the test logs."
+            exit 1
+          else
+            echo "✅ No assertion failures found."
+          fi
